#!/bin/bash
# check-secrets.sh — preflight for compose secrets.
#
# Verifies before `docker compose up` that every secret file declared in
# docker-compose.yml exists, and that every *required* secret is non-empty
# (optional ones may stay empty: ftp_*, vercel_org_id). The dense_mem_* keys
# are generated by scripts/memory-bootstrap.sh — missing or empty only
# produces a warning, so `make setup` can bootstrap them on a fresh install.
# This makes a fresh clone fail fast instead of silently starting containers
# with empty credentials.

set -u

# Required secrets (see secrets/README.md). Add new required secrets here.
REQUIRED="token telegram_allowed_chats github_token vercel_token \
openai_api_key_dispatcher openai_api_key_coder openai_api_key_qa openai_api_key_telegram \
openai_api_base_dispatcher openai_api_base_coder openai_api_base_qa openai_api_base_telegram \
postgres_password control_portal_token ai_verifier_api_key ai_verifier_api_url ai_verifier_model"

# dense_mem_* keys are generated by scripts/memory-bootstrap.sh during
# `make setup`. Missing/empty is expected before the first bootstrap and only
# warns; values that DO exist are still validated below via REQUIRED-style checks.
BOOTSTRAP="dense_mem_dispatcher dense_mem_coder dense_mem_qa"

if [ ! -f "docker-compose.yml" ]; then
  echo "❌ docker-compose.yml not found. Run this from the repo root."
  exit 1
fi

# Every file declared in the top-level compose `secrets:` map
DECLARED=$(sed -n 's#.*file: \./secrets/\([a-zA-Z0-9_]*\).*#\1#p' docker-compose.yml)

MISSING=()
for name in $DECLARED; do
  [ -f "secrets/$name" ] || MISSING+=("$name")
done

EMPTY=()
for name in $REQUIRED; do
  if [ -f "secrets/$name" ]; then
    # Empty file OR still containing its <placeholder> counts as unfilled.
    if [ ! -s "secrets/$name" ] || grep -qE '^<.*>$' "secrets/$name"; then
      EMPTY+=("$name")
    fi
  fi
done

FAILED=0
if [ "${#MISSING[@]}" -gt 0 ]; then
  FAILED=1
  echo "❌ Missing secret files (run 'make init' or create them):"
  printf '   - secrets/%s\n' "${MISSING[@]}"
fi
if [ "${#EMPTY[@]}" -gt 0 ]; then
  FAILED=1
  echo "❌ Required secret files are empty or still contain their <placeholder>:"
  printf '   - secrets/%s\n' "${EMPTY[@]}"
fi

PENDING=()
for name in $BOOTSTRAP; do
  if [ ! -f "secrets/$name" ]; then
    PENDING+=("$name — file will be created by memory-bootstrap")
  elif [ ! -s "secrets/$name" ] || grep -qE '^<.*>$' "secrets/$name"; then
    PENDING+=("$name — key will be generated by memory-bootstrap")
  fi
done
if [ "${#PENDING[@]}" -gt 0 ] && [ "$FAILED" -eq 0 ]; then
  echo "⚠️  dense-mem profile keys pending (run 'make setup' to generate):"
  printf '   - %s\n' "${PENDING[@]}"
fi

if [ "$FAILED" -eq 1 ]; then
  echo "See secrets/README.md for the full list. Refusing to start."
  exit 1
fi

echo "✅ Secrets OK: all files present, required ones non-empty."
